name: Azure Pipelines
variables:
  - group: quality
stages:
- stage: Provision
  displayName: Provisioning infrastructure
  jobs: 
  - job: CreateResources
    continueOnError: false
    pool:
        name: $(pool)
    displayName: Create Resources
    steps:
    - checkout: self
    - task: TerraformInstaller@0
      displayName: Install Terraform
      inputs:
        terraformVersion:  $(terraformVersion)
    - task: CmdLine@2
      inputs:
        script: |
          cd ~
          cd $(projectRoot)/terraform
          ls -a
          sudo apt-get update 
          sudo apt-get install zip unzip
          terraform init

    - task: TerraformCLI@0
      displayName: Terraform Plan
      inputs:
        provider: 'azurerm'
        command: 'plan'
        backendServiceArm: $(serviceConnectionName)
        backendAzureRmResourceGroupName: $(resourceGroup)
        backendAzureRmStorageAccountName: $(storageAccountName)
        backendAzureRmContainerName: 'tstate'
        backendAzureRmKey: 'terraform.tfstate'
        environmentServiceNameAzureRM: 'myServiceConn'
        workingDirectory:  $(projectRoot)/terraform/
        Configuration directory*: '$(projectRoot)/terraform/'

    - task: TerraformCLI@0
      displayName: Terraform Plan
      inputs:
        provider: 'azurerm'
        command: 'apply'
        backendServiceArm: $(serviceConnectionName)
        backendAzureRmResourceGroupName: $(resourceGroup)
        backendAzureRmStorageAccountName: $(storageAccountName)
        backendAzureRmContainerName: 'tstate'
        backendAzureRmKey: 'terraform.tfstate'
        environmentServiceNameAzureRM: 'myServiceConn'
        workingDirectory:  $(projectRoot)/terraform/
        Configuration directory*: '$(projectRoot)/terraform/'



    - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId)-fakerestapi.zip
      displayName: 'Upload FakeRestAPI Package'
      artifact: drop-fakerestapi

    # - publish: automatedtesting/selenium/functional_ui_test.py
    #   displayName: 'Upload UI Tests definition'
    #   artifact: drop-ui-tests
- stage: Build
  displayName: Build
  jobs:
  - job: Build
    pool: 
      name: $(pool)
    steps:
    - checkout: self
    - task: ArchiveFiles@2
      displayName: 'Archive FakeRestAPI'
      inputs:
        rootFolderOrFile: '/fakerestapi'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId)-fakerestapi.zip'


- stage: Deploy
  jobs:
  - deployment: DeployFakeRestAPI
    displayName: 'Deploy app to custom VM'
    pool:
      name: $(pool)
    environment: 'TEST'
    strategy:
      runOnce:
        deploy:
          steps:
            - task: AzureWebApp@1
              displayName: 'Deploy Azure Web App'
              inputs:
                azureSubscription: $(serviceConnectionName)
                appName: $(webAppName)
                appType: webApp
                package: $(Pipeline.Workspace)/drop-fakerestapi/$(Build.BuildId)-fakerestapi.zip